### ISSUE TITLE
README example invalid email

### ISSUE THREAD

**Issue by jhchen** [aef-/ex_clearbit#3]
The example on the readme is returning an error from clearbit:

```bash
iex(1) > ExClearbit.person("alex@alexmaccaw.com")                            
{:error, %{code: :email_invalid, message: "Invalid email."}}
```

Digging into it, it looks like the parameters sent to Clearbit is using a capital Email instead of lowercase so Clearbit thinks there was no email specified. The call to `Inflex.camelize(:lower)` in https://github.com/keithmattix/ex_clearbit/blob/master/lib/ex_clearbit/api/base.ex#L13 looks responsible for the capitalization. You can confirm this in iex as well:

```bash
iex(1)> Inflex.camelize("email", :lower)
"Email"
```

Removing this call to Inflex fixes the issue. Happy to submit a PR with this fix but not sure if this is the right approach.

**Comment by keithmattix** [comment]
Ah, an API changed out from under me. Please go ahead and submit a PR!

**Comment by jhchen** [comment]
Sorry for the delay. Just submitted the PR. With Inflex removed there is actually not a need for it in dependencies now but my PR was isolated to just fixing the bug. The branch I am personally using also updates the dependencies https://github.com/jhchen/ex_clearbit/commit/cdfeb49afb9b851541e472f92da23e3a3798633c. Let me know if this is a desirable addition as well.

**Comment by keithmattix** [comment]
I just merged your PR, thanks! I’d appreciate the dependency update in a separate PR for versioning purposes; thanks again!

**Comment by jhchen** [comment]
Great thanks! Submitted another PR and closing this one out.
